### ISSUE TITLE
表記ミス

### ISSUE THREAD

**Issue by kei-2000** [kazumaxneo/assemblyP#1]
### test run のサンプルコードの -c オプションが -f オプションになっています。
assemblyP -f paired_1.fq.gz -r paired_2.fq.gz -f contigs.fasta
-> assemblyP -f paired_1.fq.gz -r paired_2.fq.gz -c contigs.fasta

**Comment by kazumaxneo** [comment]
教えていただきありがとうございます。
修正しました。

**Comment by kazumaxneo** [comment]
#1 closed
